//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIforBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Job { get; set; }
        public bool CreditCard { get; set; }
        public int CreditRating { get; set; }
        public decimal Salary { get; set; }
    }
}
